## Data Science BootCamp Week 2 Take Home
#### Chapter 1, Monday sessions
By Yasamin Esmaeili

In [2]:
#   Importing base libraries
import numpy as np
import pandas as pd

### Practice Questions for Numpy
#### 1. Numpy arrays stacking

In [4]:
# Custom arrays
A = np.array([[1, 1, 1], [1, 9, 1] , [1, 1, 1]])
B = np.array([[7, 8, 9], [10, 11, 12], [13, 14, 15]])

# Vertical stacking
C = np.vstack((A, B))
print("Vertical Stacking:\n", C)

# Horizontal stacking
D = np.hstack((A, B))
print("\nHorizontal Stacking:\n", D)

Vertical Stacking:
 [[ 1  1  1]
 [ 1  9  1]
 [ 1  1  1]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]

Horizontal Stacking:
 [[ 1  1  1  7  8  9]
 [ 1  9  1 10 11 12]
 [ 1  1  1 13 14 15]]


#### 2. Common elements of two arrays
Numpy has a built-in function "intersect1d" that finds the intersection between two arrays.

In [6]:
print(f"The common elements of A and B are: {np.intersect1d(A, B)}")

The common elements of A and B are: [9]


#### 3. Elements that are within a specific range
The specific range is 5 to 10. We are going to use np.where() to extract all elements in A (or B) that are within this range.

In [ ]:
pass_range_A = np.where((A >= 5) & (A <= 10))
print(f"Elements in A within the range 5 to 10: {A[pass_range_A]}")

Elements in A within the range 5 to 10: [9]


Let's test it on B since the values have more variety.

In [ ]:
pass_range_B = np.where((B >= 5) & (B <= 10))
print(f"Elements in B within the range 5 to 10: {B[pass_range_B]}")

Elements in B within the range 5 to 10: [ 7  8  9 10]


#### 4. Filtering a large numpy array
We need to filter the rows of iris_2d that have a 3rd column>1.5 and 1st column<5

In [ ]:
# Loading the dataset
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [ ]:
iris_2d_filtered = iris_2d[np.where((iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0))]
print("\nFiltered Iris Data:\n", iris_2d_filtered)


Filtered Iris Data:
 [[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


### Practice questions for Pandas
#### 1. Filtering the data frame.

In [ ]:
# Loading the dataset
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
# print(df.keys()) # To get a sense of the columns
# df.info()
# df.describe(include='all')

In [26]:
# Only keeping the columns 'Manufacturer', 'Model' and 'Type' for every 20th row
# using step slicing by row position
df_filtered = df.iloc[0::20][['Manufacturer', 'Model', 'Type']]
print("\nFiltered DataFrame:\n", df_filtered)


Filtered DataFrame:
    Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


#### 2. Replace missing values
The question asks to replace the values in the columns 'Min.Price' and 'Max.Price' with their respective mean.

I'm assuming missing valeus are repsresnted with NaNs. In this case we can use the built-in function .fillna() to replace the missing values,

In [31]:
df_new = df.copy()
print("\nDataFrame without replacing missing values:\n", df_new[['Min.Price', 'Max.Price']].head(5))
df_new.loc[:,'Min.Price'] = df_new['Min.Price'].fillna(df_new['Min.Price'].mean())
df_new.loc[:,'Max.Price'] = df_new['Max.Price'].fillna(df_new['Max.Price'].mean())
print("\nDataFrame with replacing missing values:\n", df_new[['Min.Price', 'Max.Price']].head(5))


DataFrame without replacing missing values:
    Min.Price  Max.Price
0       12.9       18.8
1       29.2       38.7
2       25.9       32.3
3        NaN       44.6
4        NaN        NaN

DataFrame with replacing missing values:
    Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091


#### 3. Filtering a dataframe rows
This question asks for the rows of a dataframe with row sum>100.

In [43]:
# Creating a dataframe with random integers
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

In [54]:
print("All the rows of the dataframe with row sum>100:\n")
print(df.loc[df.sum(axis=1) > 100])

All the rows of the dataframe with row sum>100:

     0   1   2   3
1   26  32  31  34
3   25  35  39  15
4   34  30  35  28
6   19  36  24  30
7   12  37  29  38
10  26  31  34  28
11  32  34  10  35
13  30  21  37  30
